defaults:
  - _self_
  - override /hydra/hydra_logging: disabled
  - override /hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

step_path: ''
output_path: ''
max_interference_growth: 2.0

search:
  iteration_count: 400
  does_sample_rotation: true
  random_seed: 0
  time_budget_seconds: 600
  worker_count: 60
